version: '3.8'

services:
  cvm_runner:
    image: robortyan/near-tee-rng:latest@sha256:41f398006096809528a543796d556dee612d9dcfec6a5f542e668495c539220f
    platform: linux/amd64
    ports:
      - "3000:3000"
    environment:
      NEAR_NETWORK_ID: ${NEAR_NETWORK_ID}
      NEAR_NODE_URL: ${NEAR_NODE_URL}
      TEE_RNG_CONTRACT: ${TEE_RNG_CONTRACT}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 2G
    volumes:
      - /var/run/tappd.sock:/var/run/tappd.sock
